url: "https://mkataoka73.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/guilty_blog" # the subpath of your site, e.g. /blog
title: "guilty blog" # the name of your site, e.g. ACME Corp.
